
all : lab3-1 lab3-2 lab3-3 lab3-4 lab3-5

lab3-1: lab3-1.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab3-1 lab3-1.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab3-2: lab3-2.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab3-2 lab3-2.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab3-3: lab3-3.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab3-3 lab3-3.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab3-4: lab3-4.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab3-4 lab3-4.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab3-5: lab3-5.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab3-5 lab3-5.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

clean :
	rm lab3-1 lab3-2 lab3-3 lab3-4 lab3-5
