
all : lab1-7 lab2-1 lab2-2 lab2-3 lab2-4 lab2-5

lab1-7: lab1-7.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab1-7 lab1-7.c GL_utilities.c loadobj.c LoadTGA.c -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab2-1: lab2-1.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab2-1 lab2-1.c GL_utilities.c loadobj.c LoadTGA.c -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab2-2: lab2-2.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab2-2 lab2-2.c GL_utilities.c loadobj.c LoadTGA.c -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab2-3: lab2-3.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab2-3 lab2-3.c GL_utilities.c loadobj.c LoadTGA.c -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab2-4: lab2-4.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab2-4 lab2-4.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab2-5: lab2-5.c GL_utilities.c 
	gcc -Wall -std=c99 -o lab2-5 lab2-5.c GL_utilities.c loadobj.c LoadTGA.c VectorUtils2.c  -lGL -lglut -DGL_GLEXT_PROTOTYPES 

clean :
	rm lab1-7 lab2-1 lab2-2 lab2-3 lab2-4 lab2-5
