
all : lab1-7

lab1-1: lab1-1.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-1.c GL_utilities.c -o lab1-1 -lGL -lglut -DGL_GLEXT_PROTOTYPES 
lab1-2: lab1-2.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-2.c GL_utilities.c -o lab1-2 -lGL -lglut -DGL_GLEXT_PROTOTYPES 
lab1-3: lab1-3.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-3.c GL_utilities.c -o lab1-3 -lGL -lglut -DGL_GLEXT_PROTOTYPES 
lab1-4: lab1-4.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-4.c GL_utilities.c -o lab1-4 -lGL -lglut -DGL_GLEXT_PROTOTYPES 
lab1-5: lab1-5.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-5.c GL_utilities.c -o lab1-5 -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab1-6: lab1-6.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-6.c loadobj.c GL_utilities.c -o lab1-6 -lGL -lglut -DGL_GLEXT_PROTOTYPES 

lab1-7: lab1-7.c GL_utilities.c 
	gcc -Wall -std=c99 lab1-7.c loadobj.c GL_utilities.c -o lab1-7 -lGL -lglut -DGL_GLEXT_PROTOTYPES 

clean :
	rm lab1-1
